services:
  mysql:
    image: mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: jpacriteria
      MYSQL_USER: jpacriteria
      MYSQL_PASSWORD: jpacriteria
      TZ: 'Asia/Tokyo'
